version: '3.4'

networks:
  reaction:
    external:
      name: reaction.localhost

services:
  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:0.9
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'
 #   restart: unless-stopped
    networks:
      - reaction

  kafka:
    container_name: kafka
    image: debezium/kafka:0.9
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - '9092:9092'
    networks:
      - reaction

  elastic:
    image: elasticsearch:7.7.0
    container_name: elastic
    depends_on:
      - zookeeper
      - kafka
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
    networks:
      - reaction

  mongodb:
    image: mongo:4.0.4
    container_name: mongodb
    volumes:
      - type: volume
        source: reaction-mongodb
        target: /data/db
        read_only: false
    ports:
      - '27018:27018'
    command: --replSet replica0
    networks:
      - reaction

  connect:
    image: swarnavac/connect:1.0
    container_name: connect
    depends_on:
      - elastic
      - kafka
      - mongodb
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - BOOTSTRAP_SERVERS=elastic:9200,kafka:9092,zookeeper:2181
    #  - ADVERTISED_HOST_NAME=kafka:9092
    ports:
      - '8083:8083'
      - '8778:8778'
      - '9779:9779'
    networks:
      - reaction

volumes:
  reaction-mongodb:
